public class OffsetPagination {

    public String getRecords() {
        return null;
    }


    public PageReference End() {
        return null;
    }


    public String disableNext { get; set; }

    public PageReference Next() {
        return null;
    }


    public PageReference Previous() {
        return null;
    }


    public String getDisablePrevious() {
        return null;
    }


    public PageReference Beginning() {
        return null;
    }

}